name: NodeJS Microservices Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-services:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - api-gateway
          - user-service
          - order-service
          - payment-service
          - product-catalog-service
          - shopping-cart-service
          - notification-service

    defaults:
      run:
        working-directory: ${{ matrix.service }}

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Setup Node.js with cache per service
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      #  Install dependencies
      - name: Install dependencies
        run: npm install

      #  Build service (if build script exists)
      - name: Build service
        run: npm run build --if-present

      #  Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-build
          path: |
            ${{ matrix.service }}/dist
            ${{ matrix.service }}/build
          if-no-files-found: ignore
      - name: Build and Push to Docker Hub
      - uses: actions/checkout@v3
    name: Check out code
    uses: mr-smithers-excellent/docker-build-push@v6
    with:
      image: praveen197/demo-ci
      tags: v1, latest
      registry: registry-url.io
      dockerfile: Dockerfile.ci
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}   
